# Generated by Django 2.2 on 2021-01-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItems',
            new_name='ProfileFeedItem',
        ),
    ]
